Repository mindvalley/mv-opentelemetry, pull requests merged in 2021-10, with the labels that each got.

#5 feat: update readme/add owners
  OWNERS
  README.md
Labels: dco-signoff: yes, size/XS, lgtm

#3 Clean up pre-release
  README.md
  mix.exs
  mix.lock
Labels: dco-signoff: yes, size/S, lgtm, approved

#6 Add LICENSE and CONTRIBUTING documents
  CONTRIBUTING.md
  LICENSE.md
Labels: dco-signoff: yes, lgtm, approved, size/M
