Repository mindvalley/mv-opentelemetry, pull requests merged in 2022-12, with the labels that each got.

#40 [MVBASE-1648] Add broadway messages tracing
  lib/mv_opentelemetry.ex
  lib/mv_opentelemetry/broadway/messages.ex
  mix.lock
  mv_opentelemetry_harness/lib/mv_opentelemetry_harness/broadway_dummy.ex
  mv_opentelemetry_harness/mix.exs
  mv_opentelemetry_harness/mix.lock
  test/mv_opentelemetry/broadway/messages_test.exs
Labels: dco-signoff: yes, lgtm, approved, size/L

#39 MVBASE-1652 | Add Oban tracing
  lib/mv_opentelemetry.ex
  lib/mv_opentelemetry/oban.ex
  mix.exs
  mix.lock
  mv_opentelemetry_harness/lib/mv_opentelemetry_harness/application.ex
  mv_opentelemetry_harness/lib/mv_opentelemetry_harness/oban/job.ex
  mv_opentelemetry_harness/mix.exs
  mv_opentelemetry_harness/priv/repo/migrations/20221219113631_add_oban_migrations.exs
  test/mv_opentelemetry/oban_test.exs
Labels: dco-signoff: yes, lgtm, approved, size/L

#41 Restart app between tests
  config/test.exs
  test/mv_opentelemetry/absinthe_test.exs
  test/mv_opentelemetry/broadway/messages_test.exs
  test/mv_opentelemetry/dataloader_test.exs
  test/mv_opentelemetry/ecto_test.exs
  test/mv_opentelemetry/live_view_test.exs
  test/mv_opentelemetry/plug_test.exs
  test/mv_opentelemetry/span_tracer_test.exs
  test/support/opentelemetry_case.ex
Labels: dco-signoff: yes, lgtm, approved, size/M

#42 MVBASE-1649 | Add processing of telemetry for Finch
  lib/mv_opentelemetry.ex
  lib/mv_opentelemetry/finch.ex
  lib/mv_opentelemetry/plug.ex
  mix.exs
  mix.lock
  mv_opentelemetry_harness/mix.exs
  test/mv_opentelemetry/finch_test.exs
Labels: dco-signoff: yes, lgtm, approved, size/L

#43 MVBASE-1650 | Add semantic conventions where applicable
  lib/mv_opentelemetry/plug.ex
  test/mv_opentelemetry/plug_test.exs
Labels: dco-signoff: yes, lgtm, approved, size/M

#44 Fixed broadway tracer_id and added set current span
  lib/mv_opentelemetry/broadway/messages.ex
  mix.exs
Labels: dco-signoff: yes, size/S, lgtm, approved
