Repository mindvalley/mv-opentelemetry, pull requests merged in 2023-08, with the labels that each got.

#52 feat: add telemetry processor for Tesla
  lib/mv_opentelemetry.ex
  lib/mv_opentelemetry/tesla.ex
  mix.lock
  mv_opentelemetry_harness/mix.exs
  test/mv_opentelemetry/tesla_test.exs
Labels: dco-signoff: yes, lgtm, approved, size/L

#53 Add exception handling to Finch telemetry
  lib/mv_opentelemetry/finch.ex
Labels: dco-signoff: yes, size/S, lgtm, approved

#54 Update version, add Fadhil to reviewers
  OWNERS
  mix.exs
Labels: dco-signoff: yes, size/XS, lgtm, approved
